### ISSUE TITLE
ftdetect zon files

### ISSUE THREAD

**Issue by mitchellh** [ziglang/zig.vim#99]
Subject is self-explanatory...

**Comment by matu3ba** [comment]
Was this fixed by https://github.com/ziglang/zig.vim/commit/54c216e5306a5c3878a60596aacb94dca8652ab9 or is anything missing?

**Comment by itsfarseen** [comment]
This is not fixed because `*.zon` doesn't match `build.zig.zon`, only `build.zon`.

```diff
- au BufRead,BufNewFile *.zon setfiletype zig
+ au BufRead,BufNewFile *.zon,*.zig.zon setfiletype zig
```

**Comment by itsfarseen** [comment]
I think this is caused by vim-polyglot 
See https://github.com/folke/lazy.nvim/issues/657#issuecomment-1914079584

I fixed this by disabling vim-polyglot. It has caused many issues like this in the past for me.

**Comment by Techatrix** [comment]
fixed by 54c216e5306a5c3878a60596aacb94dca8652ab9
